// <auto-generated />
using System;
using Concert.DataAccess.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concert.DataAccess.API.Migrations
{
    [DbContext(typeof(ConcertDbContext))]
    [Migration("20250211115403_AddAuditLogToDbAndSeedTable")]
    partial class AddAuditLogToDbAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concert.Business.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Added",
                            EntityType = "SongRequest",
                            RecordId = 1,
                            Timestamp = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "9a57dbca-54e9-445e-aa05-96a623b0a4ca"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Added",
                            EntityType = "SongRequest",
                            RecordId = 2,
                            Timestamp = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "9a57dbca-54e9-445e-aa05-96a623b0a4ca"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Added",
                            EntityType = "SongRequest",
                            RecordId = 3,
                            Timestamp = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "9a57dbca-54e9-445e-aa05-96a623b0a4ca"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Added",
                            EntityType = "SongRequest",
                            RecordId = 4,
                            Timestamp = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "9a57dbca-54e9-445e-aa05-96a623b0a4ca"
                        },
                        new
                        {
                            Id = 5,
                            Action = "Added",
                            EntityType = "SongRequest",
                            RecordId = 5,
                            Timestamp = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "9a57dbca-54e9-445e-aa05-96a623b0a4ca"
                        });
                });

            modelBuilder.Entity("Concert.Business.Models.Domain.SongRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SongRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Ace of base",
                            CreatedAt = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Reggae",
                            IsDeleted = false,
                            Language = "English",
                            Title = "All that she wants"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "And One",
                            CreatedAt = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "EBM",
                            IsDeleted = false,
                            Language = "English",
                            Title = "Military fashion show"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Ascendant Vierge",
                            CreatedAt = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "EDM",
                            IsDeleted = false,
                            Language = "French",
                            Title = "Influenceur"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Boys",
                            CreatedAt = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Disco polo",
                            IsDeleted = false,
                            Language = "Polish",
                            Title = "Szalona"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Charles Aznavour",
                            CreatedAt = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Chanson française",
                            IsDeleted = false,
                            Language = "-",
                            Title = "For me Formidable"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
