// <auto-generated />
using Concert.DataAccess.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concert.DataAccess.API.Migrations
{
    [DbContext(typeof(ConcertDbContext))]
    partial class ConcertDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concert.Business.Models.Domain.SongRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SongRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Ace of base",
                            Genre = "Reggae",
                            Language = "English",
                            Title = "All that she wants"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "And One",
                            Genre = "EBM",
                            Language = "English",
                            Title = "Military fashion show"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Ascendant Vierge",
                            Genre = "EDM",
                            Language = "French",
                            Title = "Influenceur"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Boys",
                            Genre = "Disco polo",
                            Language = "Polish",
                            Title = "Szalona"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Charles Aznavour",
                            Genre = "Chanson française",
                            Language = "-",
                            Title = "For me Formidable"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
